#utils/note_decideImage.py

from models.notes_model import State, ImagePlan
from langchain_core.messages import SystemMessage, HumanMessage
from llm_config import make_chat_model
import os, re
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import requests
from dotenv import load_dotenv

from services.cloudinary_service import upload_image_bytes

load_dotenv()


llm = make_chat_model()


DECIDE_IMAGES_SYSTEM = """You are an expert technical editor.
Decide whether images/diagrams would materially improve THIS blog.

Rules:
- At most 3 images total. Prefer fewer (or none) if they don't genuinely help.
- Each image must materially improve understanding (a diagram / flow / architecture /
  comparison visual with short labels), never decoration.
- For each image, pick the section it belongs to via its index from the numbered
  SECTIONS list you are given.
- Provide: section_index, a concise image-generation prompt, alt text, a caption,
  and a bare filename (e.g. qkv_flow.png).
- Do NOT return the article text. Return strictly the ImagePlan schema (a list of
  images; an empty list if none are needed).
"""

_HEADING_RE = re.compile(r"^##\s+(.*\S)\s*$")


def decide_images(state: State) -> dict:
    merged_md = state["merged_md"]
    plan = state["plan"]
    assert plan is not None

    lines = merged_md.split("\n")
    headings = [
        (i, m.group(1)) for i, ln in enumerate(lines) if (m := _HEADING_RE.match(ln))
    ]

    if not headings:
        return {"md_with_placeholders": merged_md, "image_specs": []}

    sections_list = "\n".join(
        f"{idx}. {title}" for idx, (_, title) in enumerate(headings)
    )

    planner = llm.with_structured_output(ImagePlan)
    result = planner.invoke(
        [
            SystemMessage(content=DECIDE_IMAGES_SYSTEM),
            HumanMessage(
                content=(
                    f"Blog kind: {plan.blog_kind}\n"
                    f"Topic: {state['topic']}\n\n"
                    f"SECTIONS (choose section_index from these):\n{sections_list}\n\n"
                    "Decide the images (0-3). Do NOT echo the article text."
                )
            ),
        ]
    )

    images = (result.images or [])[:3]
    if not images:
        return {"md_with_placeholders": merged_md, "image_specs": []}

   
    inserts: dict[int, list[str]] = {}
    image_specs: list[dict] = []
    for n, img in enumerate(images, start=1):
        si = img.section_index
        if si < 0 or si >= len(headings):
            si = 0  
        line_i = headings[si][0]
        placeholder = f"[[IMAGE_{n}]]"
        inserts.setdefault(line_i, []).append(placeholder)
        image_specs.append(
            {
                "placeholder": placeholder,
                "filename": Path(img.filename).name or f"image_{n}.png",
                "alt": img.alt,
                "caption": img.caption,
                "prompt": img.prompt,
                "size": img.size,
                "quality": img.quality,
            }
        )

   
    out_lines: list[str] = []
    for i, ln in enumerate(lines):
        out_lines.append(ln)
        for placeholder in inserts.get(i, ()):
            out_lines.append("")
            out_lines.append(placeholder)

    return {"md_with_placeholders": "\n".join(out_lines), "image_specs": image_specs}


def _cf_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by the Cloudflare Workers AI worker.
    Env vars: CLOUDFARE_URL, CLOUDFARE_key.

    The worker expects POST {"prompt": ...} with `Authorization: Bearer <key>`
    and returns the image bytes directly. A browser-like User-Agent is required:
    Cloudflare's edge blocks default SDK user-agents with "error code: 1010"
    before the request ever reaches the worker.
    """
    url = os.environ.get("CLOUDFARE_URL")
    key = os.environ.get("CLOUDFARE_key")
    if not url or not key:
        raise RuntimeError("CLOUDFARE_URL / CLOUDFARE_key is not set.")

    resp = requests.post(
        url,
        json={"prompt": prompt},
        headers={
            "Authorization": f"Bearer {key}",
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
            ),
        },
        timeout=120,
    )
    resp.raise_for_status()

    content_type = resp.headers.get("content-type", "")
    if not content_type.startswith("image/"):
        # Worker returned an error payload instead of an image.
        raise RuntimeError(
            f"Cloudflare worker did not return an image (content-type={content_type!r}): "
            f"{resp.text[:200]}"
        )

    return resp.content


def _fail_block(spec: dict, err: Exception) -> str:
    """Graceful fallback so a failed image never breaks the document."""
    return (
        f"> **[IMAGE GENERATION FAILED]** {spec.get('caption','')}\n>\n"
        f"> **Alt:** {spec.get('alt','')}\n>\n"
        f"> **Prompt:** {spec.get('prompt','')}\n>\n"
        f"> **Error:** {err}\n"
    )


def generate_and_place_images(state: State) -> dict:
    plan = state["plan"]
    assert plan is not None

    md = state.get("md_with_placeholders") or state["merged_md"]
    image_specs = state.get("image_specs", []) or []

   
    if not image_specs:
        return {"final": md}

    
    def _fetch(spec: dict):
        try:
            return spec, _cf_generate_image_bytes(spec["prompt"]), None
        except Exception as e:
            return spec, None, e

    with ThreadPoolExecutor(max_workers=max(1, len(image_specs))) as ex:
        results = list(ex.map(_fetch, image_specs))

    for spec, img_bytes, err in results:
        placeholder = spec["placeholder"]

        if err is not None:
            md = md.replace(placeholder, _fail_block(spec, err))
            continue

        try:
            url = upload_image_bytes(
                img_bytes,
                filename=Path(spec["filename"]).name,
                prompt=spec.get("prompt", ""),
            )
        except Exception as e:
            md = md.replace(placeholder, _fail_block(spec, e))
            continue

        img_md = f"![{spec['alt']}]({url})\n*{spec['caption']}*"
        md = md.replace(placeholder, img_md)

    return {"final": md}